<?php
  return [
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Aba North', 'lgaAbbr' => 'EZA'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Aba South', 'lgaAbbr' => 'ABA'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Arochukwu', 'lgaAbbr' => 'ACH'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Bende', 'lgaAbbr' => 'BND'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Ikwuano', 'lgaAbbr' => 'KWU'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Isiala-Ngwa North', 'lgaAbbr' => 'KPU'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Isiala-Ngwa South', 'lgaAbbr' => 'MBA'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Isuikwuato', 'lgaAbbr' => 'MBL'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Obioma Ngwa', 'lgaAbbr' => 'NGK'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Ohafia', 'lgaAbbr' => 'HAF'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Osisioma', 'lgaAbbr' => 'SSM'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Ugwunagbo', 'lgaAbbr' => 'GWB'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Ukwa West', 'lgaAbbr' => 'KKE'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Ukwa East', 'lgaAbbr' => 'KEK'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Umuahia North', 'lgaAbbr' => 'UMA'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Umuahia South', 'lgaAbbr' => 'APR'],
    ['state' => 'Abia', 'stateAbbr' => 'AB', 'lga' => 'Umunneochi', 'lgaAbbr' => 'UNC'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Demsa', 'lgaAbbr' => 'DSA'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Fufore', 'lgaAbbr' => 'FUR'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Ganye', 'lgaAbbr' => 'GAN'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Girei', 'lgaAbbr' => 'GRE'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Gombi', 'lgaAbbr' => 'GMB'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Guyuk', 'lgaAbbr' => 'GUY'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Hong', 'lgaAbbr' => 'HNG'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Jada', 'lgaAbbr' => 'JAD'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Jimeta', 'lgaAbbr' => 'JMT'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Lamurde', 'lgaAbbr' => 'LMR'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Madagali', 'lgaAbbr' => 'MDG'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Maiha', 'lgaAbbr' => 'MAH'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Mayo-Belwa', 'lgaAbbr' => 'MWA'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Michika', 'lgaAbbr' => 'MCH'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Mubi-North', 'lgaAbbr' => 'MUB'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Mubi-South', 'lgaAbbr' => 'GYL'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Numan', 'lgaAbbr' => 'NUM'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Shelleng', 'lgaAbbr' => 'SHG'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Song', 'lgaAbbr' => 'SNG'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Toungo', 'lgaAbbr' => 'TNG'],
    ['state' => 'Adamawa', 'stateAbbr' => 'AD', 'lga' => 'Yola', 'lgaAbbr' => 'YLA'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Abak', 'lgaAbbr' => 'ABK'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Eastern-Oboi.O', 'lgaAbbr' => 'KRT'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Eket', 'lgaAbbr' => 'KET'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Esit Eket', 'lgaAbbr' => 'KST'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Essien-Udim', 'lgaAbbr' => 'AFH'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Etim-Ekpo', 'lgaAbbr' => 'AEE'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Etinam', 'lgaAbbr' => 'ETN'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Ibeno', 'lgaAbbr' => 'PNG'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Ibesikpo-Asutan', 'lgaAbbr' => 'NGD'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Ibiono-Ibom', 'lgaAbbr' => 'BMT'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Ika', 'lgaAbbr' => 'NYA'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Ikono', 'lgaAbbr' => 'KKN'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Ikot-Abasi', 'lgaAbbr' => 'KTS'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Ikot-Ekpene', 'lgaAbbr' => 'KTE'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Ini', 'lgaAbbr' => 'DRK'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Itu', 'lgaAbbr' => 'TTU'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Mbo', 'lgaAbbr' => 'ENW'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Mkpat-Enin', 'lgaAbbr' => 'MKP'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Nsit-Ibom', 'lgaAbbr' => 'AFG'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Nsit-Ubium', 'lgaAbbr' => 'KTD'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Nsit-Atai', 'lgaAbbr' => 'TAI'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Obot-Akara', 'lgaAbbr' => 'NTE'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Okobo', 'lgaAbbr' => 'KPD'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Onna', 'lgaAbbr' => 'ABT'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Oron', 'lgaAbbr' => 'RNN'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Orukanam', 'lgaAbbr' => 'KTM'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Udung-Uko', 'lgaAbbr' => 'EYF'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Ukanefun', 'lgaAbbr' => 'KPK'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Uru-Offong/Oruko', 'lgaAbbr' => 'UFG'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Uruan', 'lgaAbbr' => 'DUU'],
    ['state' => 'Akwa Ibom', 'stateAbbr' => 'AK', 'lga' => 'Uyo', 'lgaAbbr' => 'UYY'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Aguata', 'lgaAbbr' => 'AGU'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Anambra', 'lgaAbbr' => 'AAH'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Anambra-West', 'lgaAbbr' => 'NZM'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Anaocha', 'lgaAbbr' => 'NEN'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Awka-North', 'lgaAbbr' => 'ACA'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Awka-South', 'lgaAbbr' => 'AWK'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Ayamelum', 'lgaAbbr' => 'NKK'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Dunukofia', 'lgaAbbr' => 'KPP'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Ekwusigo', 'lgaAbbr' => 'ZBL'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Idemili-North', 'lgaAbbr' => 'GDD'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Idemili-South', 'lgaAbbr' => 'JJT'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Mala', 'lgaAbbr' => 'HAL'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Njikoka', 'lgaAbbr' => 'ABN'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Nnewi-North', 'lgaAbbr' => 'NNE'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Nnewi-South', 'lgaAbbr' => 'UKP'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Ogbaru', 'lgaAbbr' => 'ATN'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Onitsha-North', 'lgaAbbr' => 'NSH'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Onitsha-South', 'lgaAbbr' => 'FGG'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Orumba-North', 'lgaAbbr' => 'AJL'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Orumba-South', 'lgaAbbr' => 'UMZ'],
    ['state' => 'Anambra', 'stateAbbr' => 'AN', 'lga' => 'Oyi', 'lgaAbbr' => 'HTE'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Alkaleri', 'lgaAbbr' => 'ALK'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Bauchi', 'lgaAbbr' => 'BAU'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Bogoro', 'lgaAbbr' => 'BGR'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Damban', 'lgaAbbr' => 'DBM'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Darazo', 'lgaAbbr' => 'DRZ'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Dass', 'lgaAbbr' => 'DAS'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Gamawa', 'lgaAbbr' => 'GAM'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Ganjuwa', 'lgaAbbr' => 'GJW'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Giade', 'lgaAbbr' => 'GYD'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Itas/Gadau', 'lgaAbbr' => 'TSG'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Jama\'Are', 'lgaAbbr' => 'JMA'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Katagum', 'lgaAbbr' => 'KTG'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Kirfi', 'lgaAbbr' => 'KRF'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Misau', 'lgaAbbr' => 'MSA'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Ningi', 'lgaAbbr' => 'NNG'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Shira', 'lgaAbbr' => 'SHR'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Tafawa-Balewa', 'lgaAbbr' => 'TFB'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Toro', 'lgaAbbr' => 'TRR'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Warji', 'lgaAbbr' => 'WRJ'],
    ['state' => 'Bauchi', 'stateAbbr' => 'BA', 'lga' => 'Zaki', 'lgaAbbr' => 'ZAK'],
    ['state' => 'Bayelsa', 'stateAbbr' => 'BY', 'lga' => 'Brass', 'lgaAbbr' => 'BRS'],
    ['state' => 'Bayelsa', 'stateAbbr' => 'BY', 'lga' => 'Ekeremor', 'lgaAbbr' => 'KMR'],
    ['state' => 'Bayelsa', 'stateAbbr' => 'BY', 'lga' => 'Kolokuma/Opkuma', 'lgaAbbr' => 'KMK'],
    ['state' => 'Bayelsa', 'stateAbbr' => 'BY', 'lga' => 'Nembe', 'lgaAbbr' => 'NEM'],
    ['state' => 'Bayelsa', 'stateAbbr' => 'BY', 'lga' => 'Ogbia', 'lgaAbbr' => 'GBB'],
    ['state' => 'Bayelsa', 'stateAbbr' => 'BY', 'lga' => 'Sagbama', 'lgaAbbr' => 'SAG'],
    ['state' => 'Bayelsa', 'stateAbbr' => 'BY', 'lga' => 'Southern Ijaw', 'lgaAbbr' => 'SPR'],
    ['state' => 'Bayelsa', 'stateAbbr' => 'BY', 'lga' => 'Yenegoa', 'lgaAbbr' => 'YEN'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Ado', 'lgaAbbr' => 'GMU'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Agatu', 'lgaAbbr' => 'GTU'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Apa', 'lgaAbbr' => 'GKP'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Buruku', 'lgaAbbr' => 'BKB'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Gboko', 'lgaAbbr' => 'GBK'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Guma', 'lgaAbbr' => 'YGJ'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Gwer-East', 'lgaAbbr' => 'ALD'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Gwer-West', 'lgaAbbr' => 'NAK'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Katsina-Ala', 'lgaAbbr' => 'KAL'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Konshisha', 'lgaAbbr' => 'TSE'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Kwande', 'lgaAbbr' => 'WDP'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Logo', 'lgaAbbr' => 'GBG'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Makurdi', 'lgaAbbr' => 'MKD'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Obi', 'lgaAbbr' => 'BRT'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Ogbadibo', 'lgaAbbr' => 'BGT'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Ohimini', 'lgaAbbr' => 'DKP'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Oju', 'lgaAbbr' => 'JUX'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Okpokwu', 'lgaAbbr' => 'PKG'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Otukpo', 'lgaAbbr' => 'TKP'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Tarka', 'lgaAbbr' => 'WNN'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Ukum', 'lgaAbbr' => 'UKM'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Ushongo', 'lgaAbbr' => 'SEL'],
    ['state' => 'Benue', 'stateAbbr' => 'BN', 'lga' => 'Vandeikya', 'lgaAbbr' => 'VDY'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Abadam', 'lgaAbbr' => 'ADM'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Askira-Uba', 'lgaAbbr' => 'ASU'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Bama', 'lgaAbbr' => 'BAM'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Bayo', 'lgaAbbr' => 'BAY'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Biu', 'lgaAbbr' => 'BBU'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Chibok', 'lgaAbbr' => 'CBK'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Damboa', 'lgaAbbr' => 'DAM'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Dikwa', 'lgaAbbr' => 'DKW'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Gubio', 'lgaAbbr' => 'GUB'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Guzamala', 'lgaAbbr' => 'GZM'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Gwoza', 'lgaAbbr' => 'GZA'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Hawul', 'lgaAbbr' => 'HWL'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Jere', 'lgaAbbr' => 'JRE'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Kaga', 'lgaAbbr' => 'KGG'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Kala/Balge', 'lgaAbbr' => 'KBG'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Konduga', 'lgaAbbr' => 'KDG'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Kukawa', 'lgaAbbr' => 'KWA'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Kwaya-Kusar', 'lgaAbbr' => 'KWY'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Mafa', 'lgaAbbr' => 'MAF'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Magumeri', 'lgaAbbr' => 'MGM'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Maiduguri', 'lgaAbbr' => 'MAG'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Marte', 'lgaAbbr' => 'MAR'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Mobbar', 'lgaAbbr' => 'MBR'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Mongunu', 'lgaAbbr' => 'MNG'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Ngala', 'lgaAbbr' => 'NGL'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Nganzai', 'lgaAbbr' => 'NGZ'],
    ['state' => 'Borno', 'stateAbbr' => 'BO', 'lga' => 'Shani', 'lgaAbbr' => 'SHN'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Abi', 'lgaAbbr' => 'TGD'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Akamkpa', 'lgaAbbr' => 'RAM'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Akpabuyo', 'lgaAbbr' => 'KTA'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Bakassi', 'lgaAbbr' => 'BKS'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Bekwara', 'lgaAbbr' => 'ABE'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Biase', 'lgaAbbr' => 'AKP'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Boki', 'lgaAbbr' => 'BJE'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Calabar-Municipal', 'lgaAbbr' => 'CAL'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Calabar-South', 'lgaAbbr' => 'ANA'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Etunk', 'lgaAbbr' => 'EFE'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Ikom', 'lgaAbbr' => 'KMM'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Obanliku', 'lgaAbbr' => 'BNS'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Obubra', 'lgaAbbr' => 'BRA'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Obudu', 'lgaAbbr' => 'UDU'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Odukpani', 'lgaAbbr' => 'DUK'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Ogoja', 'lgaAbbr' => 'GGJ'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Yakurr', 'lgaAbbr' => 'GEP'],
    ['state' => 'Cross River', 'stateAbbr' => 'CR', 'lga' => 'Yala', 'lgaAbbr' => 'CKK'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Aniocha-North', 'lgaAbbr' => 'SLK'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Aniocha-South', 'lgaAbbr' => 'GWK'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Bomadi', 'lgaAbbr' => 'BMA'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Burutu', 'lgaAbbr' => 'BUR'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Ethiope-East', 'lgaAbbr' => 'SKL'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Ethiope-West', 'lgaAbbr' => 'GRA'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Ika-North', 'lgaAbbr' => 'AGB'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Ika-South', 'lgaAbbr' => 'AYB'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Isoko-North', 'lgaAbbr' => 'DSZ'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Isoko-South', 'lgaAbbr' => 'LEH'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Ndokwa-East', 'lgaAbbr' => 'ABH'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Ndokwa-West', 'lgaAbbr' => 'KWC'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Okpe', 'lgaAbbr' => 'KPE'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Oshimili-North', 'lgaAbbr' => 'AKU'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Oshimili', 'lgaAbbr' => 'ASB'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Patani', 'lgaAbbr' => 'PTN'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Sapele', 'lgaAbbr' => 'SAP'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Udu', 'lgaAbbr' => 'ALA'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Ughelli-North', 'lgaAbbr' => 'UGH'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Ughelli-South', 'lgaAbbr' => 'JRT'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Ukwuani', 'lgaAbbr' => 'BKW'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Uvwie', 'lgaAbbr' => 'EFR'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Warri-Central', 'lgaAbbr' => 'GBJ'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Warri-North', 'lgaAbbr' => 'KLK'],
    ['state' => 'Delta', 'stateAbbr' => 'DT', 'lga' => 'Warri-South', 'lgaAbbr' => 'WWR'],
    ['state' => 'Ebonyi', 'stateAbbr' => 'EB', 'lga' => 'Abakaliki', 'lgaAbbr' => 'AKL'],
    ['state' => 'Ebonyi', 'stateAbbr' => 'EB', 'lga' => 'Afikpo-North', 'lgaAbbr' => 'AFK'],
    ['state' => 'Ebonyi', 'stateAbbr' => 'EB', 'lga' => 'Afikpo-South', 'lgaAbbr' => 'EDA'],
    ['state' => 'Ebonyi', 'stateAbbr' => 'EB', 'lga' => 'Ebonyi', 'lgaAbbr' => 'UGB'],
    ['state' => 'Ebonyi', 'stateAbbr' => 'EB', 'lga' => 'Ezza-North', 'lgaAbbr' => 'EBJ'],
    ['state' => 'Ebonyi', 'stateAbbr' => 'EB', 'lga' => 'Ezza-South', 'lgaAbbr' => 'NKE'],
    ['state' => 'Ebonyi', 'stateAbbr' => 'EB', 'lga' => 'Ikwo', 'lgaAbbr' => 'CHR'],
    ['state' => 'Ebonyi', 'stateAbbr' => 'EB', 'lga' => 'Ishielu', 'lgaAbbr' => 'ZLL'],
    ['state' => 'Ebonyi', 'stateAbbr' => 'EB', 'lga' => 'Ivo', 'lgaAbbr' => 'SKA'],
    ['state' => 'Ebonyi', 'stateAbbr' => 'EB', 'lga' => 'Izzi', 'lgaAbbr' => 'BKL'],
    ['state' => 'Ebonyi', 'stateAbbr' => 'EB', 'lga' => 'Ohakwu', 'lgaAbbr' => 'HKW'],
    ['state' => 'Ebonyi', 'stateAbbr' => 'EB', 'lga' => 'Ohaozara', 'lgaAbbr' => 'BZR'],
    ['state' => 'Ebonyi', 'stateAbbr' => 'EB', 'lga' => 'Onicha', 'lgaAbbr' => 'NCA'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Akoko-Edo', 'lgaAbbr' => 'GAR'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Egor', 'lgaAbbr' => 'USL'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Esan-Central', 'lgaAbbr' => 'RRU'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Esan-North-East', 'lgaAbbr' => 'URM'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Esan-South-East', 'lgaAbbr' => 'UBJ'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Esan-West', 'lgaAbbr' => 'EKP'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Etsako-Central', 'lgaAbbr' => 'FUG'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Etsako-East', 'lgaAbbr' => 'AGD'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Etsako-West', 'lgaAbbr' => 'AUC'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Igueben', 'lgaAbbr' => 'GUE'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Ikpoba-Okha', 'lgaAbbr' => 'DGE'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Oredo', 'lgaAbbr' => 'BEN'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Orhionmwon', 'lgaAbbr' => 'ABD'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Ovia-North-East', 'lgaAbbr' => 'AKA'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Ovia-South-West', 'lgaAbbr' => 'GBZ'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Owan-East', 'lgaAbbr' => 'AFZ'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Owan-West', 'lgaAbbr' => 'SGD'],
    ['state' => 'Edo', 'stateAbbr' => 'ED', 'lga' => 'Uhunmwonde', 'lgaAbbr' => 'HER'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Ado-Ekiti', 'lgaAbbr' => 'ADK'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Efon', 'lgaAbbr' => 'EFY'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Ekiti-East', 'lgaAbbr' => 'MUE'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Ekiti-South-West', 'lgaAbbr' => 'LAW'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Ekiti-West', 'lgaAbbr' => 'AMK'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Emure', 'lgaAbbr' => 'EMR'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Ise-Orun', 'lgaAbbr' => 'SSE'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Gbonyin', 'lgaAbbr' => 'DEA'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Ido-Osi', 'lgaAbbr' => 'DEK'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Ijero', 'lgaAbbr' => 'JER'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Ikere', 'lgaAbbr' => 'KER'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Ikole', 'lgaAbbr' => 'RLE'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Ilejemeje', 'lgaAbbr' => 'YEK'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Irepodun/Ifelodun', 'lgaAbbr' => 'GED'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Moba', 'lgaAbbr' => 'TUN'],
    ['state' => 'Ekiti', 'stateAbbr' => 'EK', 'lga' => 'Oye', 'lgaAbbr' => 'YEE'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Aninri', 'lgaAbbr' => 'DBR'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Awgu', 'lgaAbbr' => 'AWG'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Enugu-East', 'lgaAbbr' => 'NKW'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Enugu-North', 'lgaAbbr' => 'ENU'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Enugu-South', 'lgaAbbr' => 'UWN'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Ezeagu', 'lgaAbbr' => 'AGW'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Igbo-Etti', 'lgaAbbr' => 'GBD'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Igbo-Eze-North', 'lgaAbbr' => 'ENZ'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Igbo-Eze-South', 'lgaAbbr' => 'BBG'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Isi-Uzo', 'lgaAbbr' => 'KEM'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Nkanu-East', 'lgaAbbr' => 'MGL'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Nkanu-West', 'lgaAbbr' => 'AGN'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Nsukka', 'lgaAbbr' => 'NSK'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Oji-River', 'lgaAbbr' => 'JRV'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Udenu', 'lgaAbbr' => 'BLF'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Udi', 'lgaAbbr' => 'UDD'],
    ['state' => 'Enugu', 'stateAbbr' => 'EN', 'lga' => 'Uzo-Uwani', 'lgaAbbr' => 'UMU'],
    ['state' => 'FCT', 'stateAbbr' => 'FC', 'lga' => 'Abaji Area Council', 'lgaAbbr' => 'ABJ'],
    ['state' => 'FCT', 'stateAbbr' => 'FC', 'lga' => 'Abuja Municipal Area Council', 'lgaAbbr' => 'ABC'],
    ['state' => 'FCT', 'stateAbbr' => 'FC', 'lga' => 'Bwari', 'lgaAbbr' => 'BWR'],
    ['state' => 'FCT', 'stateAbbr' => 'FC', 'lga' => 'Gwagwalada', 'lgaAbbr' => 'GWA'],
    ['state' => 'FCT', 'stateAbbr' => 'FC', 'lga' => 'Kuje Area Council', 'lgaAbbr' => 'KUJ'],
    ['state' => 'FCT', 'stateAbbr' => 'FC', 'lga' => 'Kwali', 'lgaAbbr' => 'KWL'],
    ['state' => 'Gombe', 'stateAbbr' => 'GB', 'lga' => 'Akko', 'lgaAbbr' => 'AKK'],
    ['state' => 'Gombe', 'stateAbbr' => 'GB', 'lga' => 'Balanga', 'lgaAbbr' => 'BLG'],
    ['state' => 'Gombe', 'stateAbbr' => 'GB', 'lga' => 'Billiri', 'lgaAbbr' => 'BLR'],
    ['state' => 'Gombe', 'stateAbbr' => 'GB', 'lga' => 'Dukku', 'lgaAbbr' => 'DKU'],
    ['state' => 'Gombe', 'stateAbbr' => 'GB', 'lga' => 'Funakaye', 'lgaAbbr' => 'FKY'],
    ['state' => 'Gombe', 'stateAbbr' => 'GB', 'lga' => 'Gombe', 'lgaAbbr' => 'GME'],
    ['state' => 'Gombe', 'stateAbbr' => 'GB', 'lga' => 'Kaltungo', 'lgaAbbr' => 'KLT'],
    ['state' => 'Gombe', 'stateAbbr' => 'GB', 'lga' => 'Kwami', 'lgaAbbr' => 'KWM'],
    ['state' => 'Gombe', 'stateAbbr' => 'GB', 'lga' => 'Nafada/Bajoga', 'lgaAbbr' => 'NFD'],
    ['state' => 'Gombe', 'stateAbbr' => 'GB', 'lga' => 'Shomgom', 'lgaAbbr' => 'SHM'],
    ['state' => 'Gombe', 'stateAbbr' => 'GB', 'lga' => 'Yamaltu/Deba', 'lgaAbbr' => 'YDB'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Aboh-Mbaise', 'lgaAbbr' => 'ABB'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Ahiazu-Mbaise', 'lgaAbbr' => 'AFR'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Ehime-Mbano', 'lgaAbbr' => 'EHM'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Ezinihitte', 'lgaAbbr' => 'ETU'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Ideato-North', 'lgaAbbr' => 'URU'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Ideato-South', 'lgaAbbr' => 'DFB'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Ihitte/Uboma', 'lgaAbbr' => 'EKE'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Ikeduru', 'lgaAbbr' => 'KED'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Isiala-Mbano', 'lgaAbbr' => 'UML'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Isu', 'lgaAbbr' => 'UMD'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Mbaitoli', 'lgaAbbr' => 'NWA'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Ngor-Okpala', 'lgaAbbr' => 'NGN'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Njaba', 'lgaAbbr' => 'UMK'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Nkwerre', 'lgaAbbr' => 'NKR'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Nwangele', 'lgaAbbr' => 'AMG'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Obowo', 'lgaAbbr' => 'TTK'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Oguta', 'lgaAbbr' => 'GUA'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Ohaji-Egbema', 'lgaAbbr' => 'EBM'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Okigwe', 'lgaAbbr' => 'KGE'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Onuimo', 'lgaAbbr' => 'KWE'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Orlu', 'lgaAbbr' => 'RLU'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Orsu', 'lgaAbbr' => 'AWT'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Oru-East', 'lgaAbbr' => 'MMA'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Oru-West', 'lgaAbbr' => 'NGB'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Owerri-Municipal', 'lgaAbbr' => 'WER'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Owerri-North', 'lgaAbbr' => 'RRT'],
    ['state' => 'Imo', 'stateAbbr' => 'IM', 'lga' => 'Owerri-West', 'lgaAbbr' => 'UMG'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Auyo', 'lgaAbbr' => 'AUY'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Babura', 'lgaAbbr' => 'BBR'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Biriniwa', 'lgaAbbr' => 'BNW'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Birnin-Kudu', 'lgaAbbr' => 'BKD'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Buji', 'lgaAbbr' => 'BUJ'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Dutse', 'lgaAbbr' => 'dut'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Gagarawa', 'lgaAbbr' => 'GGW'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Garki', 'lgaAbbr' => 'GRK'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Gumel', 'lgaAbbr' => 'GML'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Guri', 'lgaAbbr' => 'GRR'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Gwaram', 'lgaAbbr' => 'GRM'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Gwiwa', 'lgaAbbr' => 'GWW'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Hadejia', 'lgaAbbr' => 'HJA'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Jahun', 'lgaAbbr' => 'JHN'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Kafin-Hausa', 'lgaAbbr' => 'KHS'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Kaugama', 'lgaAbbr' => 'KGM'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Kazaure', 'lgaAbbr' => 'KZR'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Kirkasamma', 'lgaAbbr' => 'KKM'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Maigatari', 'lgaAbbr' => 'MGR'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Malam-Maduri', 'lgaAbbr' => 'MMR'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Miga', 'lgaAbbr' => 'MGA'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Ringim', 'lgaAbbr' => 'RNG'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Roni', 'lgaAbbr' => 'RRN'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Sule-Tankarkar', 'lgaAbbr' => 'STK'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Taura', 'lgaAbbr' => 'TAR'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Yankwashi', 'lgaAbbr' => 'YKS'],
    ['state' => 'Jigawa', 'stateAbbr' => 'JG', 'lga' => 'Kiyawa', 'lgaAbbr' => 'KYW'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Birnin-Gwari', 'lgaAbbr' => 'BNG'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Chikun', 'lgaAbbr' => 'KJM'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Giwa', 'lgaAbbr' => 'GKW'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Igabi', 'lgaAbbr' => 'TRK'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Ikara', 'lgaAbbr' => 'KAR'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Jaba', 'lgaAbbr' => 'KWB'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Jemaa', 'lgaAbbr' => 'KAF'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Kachia', 'lgaAbbr' => 'KCH'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Kaduna-North', 'lgaAbbr' => 'DKA'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Kagarko', 'lgaAbbr' => 'KGK'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Kajuru', 'lgaAbbr' => 'KJR'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Kaura', 'lgaAbbr' => 'KRA'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Kaduna-South', 'lgaAbbr' => 'MKA'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Kauru', 'lgaAbbr' => 'KRU'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Kubah', 'lgaAbbr' => 'ANC'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Kudan', 'lgaAbbr' => 'HKY'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Lere', 'lgaAbbr' => 'SNK'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Makarfi', 'lgaAbbr' => 'MKR'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Sabon-Gari', 'lgaAbbr' => 'SBG'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Sanga', 'lgaAbbr' => 'GWT'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Soba', 'lgaAbbr' => 'MGN'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Zangon-Kataf', 'lgaAbbr' => 'ZKW'],
    ['state' => 'Kaduna', 'stateAbbr' => 'KD', 'lga' => 'Zaria', 'lgaAbbr' => 'ZAR'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Ajingi', 'lgaAbbr' => 'AJG'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Albasu', 'lgaAbbr' => 'ABS'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Bagwa', 'lgaAbbr' => 'BGW'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Bebeji', 'lgaAbbr' => 'BBJ'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Bichi', 'lgaAbbr' => 'BCH'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Bunkure', 'lgaAbbr' => 'BNK'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Dala', 'lgaAbbr' => 'DAL'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Danbatta', 'lgaAbbr' => 'DBT'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Dawakin-Kudu', 'lgaAbbr' => 'DKD'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Dawakin-Tofa', 'lgaAbbr' => 'DTF'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Doguwa', 'lgaAbbr' => 'DGW'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Fagge', 'lgaAbbr' => 'FGE'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Gabasawa', 'lgaAbbr' => 'DSW'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Garko', 'lgaAbbr' => 'GAK'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Garun-Mallam', 'lgaAbbr' => 'GNM'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Gaya', 'lgaAbbr' => 'GYA'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Gezawa', 'lgaAbbr' => 'GZW'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Gwale', 'lgaAbbr' => 'GWL'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Gwarzo', 'lgaAbbr' => 'GRZ'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Kano-Municipal', 'lgaAbbr' => 'KMC'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Karaye', 'lgaAbbr' => 'KRY'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Kibiya', 'lgaAbbr' => 'KBY'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Kiru', 'lgaAbbr' => 'KKU'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Kumbotso', 'lgaAbbr' => 'KBT'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Kunchi', 'lgaAbbr' => 'KNC'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Kura', 'lgaAbbr' => 'KUR'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Madobi', 'lgaAbbr' => 'MDB'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Makoda', 'lgaAbbr' => 'MKK'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Minjibir', 'lgaAbbr' => 'MJB'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Nassarawa', 'lgaAbbr' => 'NSR'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Rano', 'lgaAbbr' => 'RAN'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Rimin-Gado', 'lgaAbbr' => 'RMG'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Rogo', 'lgaAbbr' => 'RGG'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Shanono', 'lgaAbbr' => 'SNN'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Sumaila', 'lgaAbbr' => 'SML'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Takai', 'lgaAbbr' => 'TAK'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Tarauni', 'lgaAbbr' => 'TRN'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Tofa', 'lgaAbbr' => 'TEA'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Tsanyawa', 'lgaAbbr' => 'TYW'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Tudun-Wada', 'lgaAbbr' => 'TWD'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Ungogo', 'lgaAbbr' => 'UGG'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Warawa', 'lgaAbbr' => 'WRA'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Wudil', 'lgaAbbr' => 'WDL'],
    ['state' => 'Kano', 'stateAbbr' => 'KN', 'lga' => 'Kabo', 'lgaAbbr' => 'KBK'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Bakori', 'lgaAbbr' => 'BKR'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Batagarawa', 'lgaAbbr' => 'BAT'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Batsari', 'lgaAbbr' => 'BTR'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Baure', 'lgaAbbr' => 'BRE'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Bixdawa', 'lgaAbbr' => 'BDW'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Charanchi', 'lgaAbbr' => 'CRC'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Dan-Musa', 'lgaAbbr' => 'DMS'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Dandume', 'lgaAbbr' => 'DDM'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Danja', 'lgaAbbr' => 'DJA'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Daura', 'lgaAbbr' => 'DRA'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Dutsi', 'lgaAbbr' => 'DTS'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Dutsinma', 'lgaAbbr' => 'DTM'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Faskari', 'lgaAbbr' => 'FSK'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Funtua', 'lgaAbbr' => 'FTA'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Ingawa', 'lgaAbbr' => 'NGW'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Jibia', 'lgaAbbr' => 'JBY'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Kafur', 'lgaAbbr' => 'KFR'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Ka1ta', 'lgaAbbr' => 'KAT'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Kankara', 'lgaAbbr' => 'KKR'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Kankia', 'lgaAbbr' => 'KNK'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Katsina', 'lgaAbbr' => 'KTN'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Kurfi', 'lgaAbbr' => 'KUF'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Kusada', 'lgaAbbr' => 'KSD'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Mai-Adua', 'lgaAbbr' => 'MDW'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Malumfashi', 'lgaAbbr' => 'MNF'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Maxi', 'lgaAbbr' => 'MAN'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Mashi', 'lgaAbbr' => 'MSH'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Matazu', 'lgaAbbr' => 'MTZ'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Musawa', 'lgaAbbr' => 'MSW'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Rimi', 'lgaAbbr' => 'RMY'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Sabuwa', 'lgaAbbr' => 'SBA'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Safana', 'lgaAbbr' => 'SFN'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Sandamu', 'lgaAbbr' => 'SDM'],
    ['state' => 'Katsina', 'stateAbbr' => 'KT', 'lga' => 'Zango', 'lgaAbbr' => 'ZNG'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Aleiro', 'lgaAbbr' => 'ALR'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Arewa-Dandi', 'lgaAbbr' => 'KGW'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Argungu', 'lgaAbbr' => 'ARG'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Augie', 'lgaAbbr' => 'AUG'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Bagudo', 'lgaAbbr' => 'BGD'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Birnin-Kebbi', 'lgaAbbr' => 'BRK'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Bunza', 'lgaAbbr' => 'BNZ'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Dandi', 'lgaAbbr' => 'KMB'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Fakai', 'lgaAbbr' => 'MHT'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Gwandu', 'lgaAbbr' => 'GWN'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Jega', 'lgaAbbr' => 'JEG'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Kalgo', 'lgaAbbr' => 'KLG'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Koko-Besse', 'lgaAbbr' => 'BES'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Maiyama', 'lgaAbbr' => 'MYM'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Ngaski', 'lgaAbbr' => 'WRR'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Sakaba', 'lgaAbbr' => 'DRD'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Shanga', 'lgaAbbr' => 'SNA'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Suru', 'lgaAbbr' => 'DKG'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Wasagu', 'lgaAbbr' => 'RBH'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Yauri', 'lgaAbbr' => 'YLW'],
    ['state' => 'Kebbi', 'stateAbbr' => 'KB', 'lga' => 'Zuru', 'lgaAbbr' => 'ZUR'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Adavi', 'lgaAbbr' => 'DAV'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Ajaokuta', 'lgaAbbr' => 'AJA'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Ankpa', 'lgaAbbr' => 'KPA'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Bassa', 'lgaAbbr' => 'BAS'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Dekina', 'lgaAbbr' => 'KNA'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Ibaji', 'lgaAbbr' => 'NDG'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Idah', 'lgaAbbr' => 'DAH'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Igalamela-Odolu', 'lgaAbbr' => 'AJK'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Ijumu', 'lgaAbbr' => 'JMU'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Kabba/Bunu', 'lgaAbbr' => 'KAB'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Kogi', 'lgaAbbr' => 'KKF'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Lokoja', 'lgaAbbr' => 'LKJ'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Mopa-Muro-Mopi', 'lgaAbbr' => 'MPA'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Ofu', 'lgaAbbr' => 'KFU'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Ogori/Magongo', 'lgaAbbr' => 'KPF'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Okehi', 'lgaAbbr' => 'KKH'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Okene', 'lgaAbbr' => 'KNE'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Olamaboro', 'lgaAbbr' => 'LAM'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Omala', 'lgaAbbr' => 'BJK'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Yagba-East', 'lgaAbbr' => 'ERE'],
    ['state' => 'Kogi', 'stateAbbr' => 'KG', 'lga' => 'Yagba-West', 'lgaAbbr' => 'SAN'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Asa', 'lgaAbbr' => 'AFN'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Baruten', 'lgaAbbr' => 'KSB'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Edu', 'lgaAbbr' => 'LAF'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Ekiti', 'lgaAbbr' => 'ARP'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Ifelodun', 'lgaAbbr' => 'SHA'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Ilorin-East', 'lgaAbbr' => 'KEY'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Ilorin-South', 'lgaAbbr' => 'FUF'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Ilorin-West', 'lgaAbbr' => 'LRN'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Irepodun', 'lgaAbbr' => 'MUN'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Isin', 'lgaAbbr' => 'WSN'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Kaiama', 'lgaAbbr' => 'KMA'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Moro', 'lgaAbbr' => 'BDU'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Offa', 'lgaAbbr' => 'FFA'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Oke-Ero', 'lgaAbbr' => 'LFF'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Oyun', 'lgaAbbr' => 'LEM'],
    ['state' => 'Kwara', 'stateAbbr' => 'KW', 'lga' => 'Pategi', 'lgaAbbr' => 'PTG'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Agege', 'lgaAbbr' => 'GGE'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Ajeromi - Ifelodun', 'lgaAbbr' => 'AGL'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Alimosho', 'lgaAbbr' => 'KTU'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Amuwo-Odofin', 'lgaAbbr' => 'FST'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Apapa', 'lgaAbbr' => 'APP'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Badagry', 'lgaAbbr' => 'BDG'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Epe', 'lgaAbbr' => 'EPE'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Eti-Osa', 'lgaAbbr' => 'EKY'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Ibeju-Lekki', 'lgaAbbr' => 'AKD'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Ifako Ijaiye', 'lgaAbbr' => 'FKJ'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Ikeja', 'lgaAbbr' => 'KJA'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Ikorodu', 'lgaAbbr' => 'KRD'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Kosofe', 'lgaAbbr' => 'KSF'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Lagos-Island', 'lgaAbbr' => 'AAA'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Lagos-Mainland', 'lgaAbbr' => 'LND'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Mushin', 'lgaAbbr' => 'MUS'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Ojo', 'lgaAbbr' => 'JJJ'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Oshodi Isolo', 'lgaAbbr' => 'LSD'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Somolu', 'lgaAbbr' => 'SMK'],
    ['state' => 'Lagos', 'stateAbbr' => 'LA', 'lga' => 'Surulere', 'lgaAbbr' => 'LSR'],
    ['state' => 'Nasarawa', 'stateAbbr' => 'NS', 'lga' => 'Akwanga', 'lgaAbbr' => 'AKW'],
    ['state' => 'Nasarawa', 'stateAbbr' => 'NS', 'lga' => 'Awe', 'lgaAbbr' => 'AWE'],
    ['state' => 'Nasarawa', 'stateAbbr' => 'NS', 'lga' => 'Doma', 'lgaAbbr' => 'DMA'],
    ['state' => 'Nasarawa', 'stateAbbr' => 'NS', 'lga' => 'Karu', 'lgaAbbr' => 'KRV'],
    ['state' => 'Nasarawa', 'stateAbbr' => 'NS', 'lga' => 'Keana', 'lgaAbbr' => 'KEN'],
    ['state' => 'Nasarawa', 'stateAbbr' => 'NS', 'lga' => 'Keffi', 'lgaAbbr' => 'KEF'],
    ['state' => 'Nasarawa', 'stateAbbr' => 'NS', 'lga' => 'Kokona', 'lgaAbbr' => 'GRU'],
    ['state' => 'Nasarawa', 'stateAbbr' => 'NS', 'lga' => 'Lafia', 'lgaAbbr' => 'LFA'],
    ['state' => 'Nasarawa', 'stateAbbr' => 'NS', 'lga' => 'Nasarawa', 'lgaAbbr' => 'NSW'],
    ['state' => 'Nasarawa', 'stateAbbr' => 'NS', 'lga' => 'Nasarawa-Eggon', 'lgaAbbr' => 'NEG'],
    ['state' => 'Nasarawa', 'stateAbbr' => 'NS', 'lga' => 'Obi', 'lgaAbbr' => 'NBB'],
    ['state' => 'Nasarawa', 'stateAbbr' => 'NS', 'lga' => 'Wamba', 'lgaAbbr' => 'WAM'],
    ['state' => 'Nasarawa', 'stateAbbr' => 'NS', 'lga' => 'Toto', 'lgaAbbr' => 'NTT'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Agaie', 'lgaAbbr' => 'AGA'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Agwara', 'lgaAbbr' => 'AGR'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Bida', 'lgaAbbr' => 'BDA'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Borgu', 'lgaAbbr' => 'NBS'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Bosso', 'lgaAbbr' => 'MAK'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Chanchaga', 'lgaAbbr' => 'MNA'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Edati', 'lgaAbbr' => 'ENG'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Gbako', 'lgaAbbr' => 'LMU'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Gurara', 'lgaAbbr' => 'GWU'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Katcha', 'lgaAbbr' => 'KHA'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Kontagora', 'lgaAbbr' => 'KNT'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Lapai', 'lgaAbbr' => 'LAP'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Lavun', 'lgaAbbr' => 'KUG'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Magama', 'lgaAbbr' => 'NAS'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Mariga', 'lgaAbbr' => 'BMG'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Mashegu', 'lgaAbbr' => 'MSG'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Mokwa', 'lgaAbbr' => 'MKW'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Muya', 'lgaAbbr' => 'SRP'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Paikoro', 'lgaAbbr' => 'PAK'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Rafi', 'lgaAbbr' => 'KAG'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Rijau', 'lgaAbbr' => 'RJA'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Shiroro', 'lgaAbbr' => 'KUT'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Suleja', 'lgaAbbr' => 'SUL'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Tafa', 'lgaAbbr' => 'WSE'],
    ['state' => 'Niger', 'stateAbbr' => 'NG', 'lga' => 'Wushishi', 'lgaAbbr' => 'WSU'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Abeokuta-North', 'lgaAbbr' => 'AKM'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Abeokuta-South', 'lgaAbbr' => 'AAB'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Adoodo/Ota', 'lgaAbbr' => 'OTA'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Ewekoro', 'lgaAbbr' => 'TRE'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Ifo', 'lgaAbbr' => 'FFF'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Egbado-North', 'lgaAbbr' => 'AYE'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Egbado-South', 'lgaAbbr' => 'LAR'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Ijebu-East', 'lgaAbbr' => 'GBE'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Ijebu-North', 'lgaAbbr' => 'JGB'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Ijebu-North-East', 'lgaAbbr' => 'JNE'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Ijebu-Ode', 'lgaAbbr' => 'JBD'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Ikenne', 'lgaAbbr' => 'KNN'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Imeko-Afon', 'lgaAbbr' => 'MEK'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Ipokia', 'lgaAbbr' => 'PKA'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Obafemi Owode', 'lgaAbbr' => 'WDE'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Odedah', 'lgaAbbr' => 'DED'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Odogbolu', 'lgaAbbr' => 'DGB'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Ogun-Waterside', 'lgaAbbr' => 'ABG'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Remo-North', 'lgaAbbr' => 'JRM'],
    ['state' => 'Ogun', 'stateAbbr' => 'OG', 'lga' => 'Shagamu', 'lgaAbbr' => 'SMG'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Akoko-North', 'lgaAbbr' => 'KAK'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Akoko-North-West', 'lgaAbbr' => 'ANG'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Akoko South', 'lgaAbbr' => 'SUA'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Akoko-South-East', 'lgaAbbr' => 'KAA'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Akure-North', 'lgaAbbr' => 'AKR'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Akure-South', 'lgaAbbr' => 'JTA'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Ese-Odo', 'lgaAbbr' => 'GKB'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Idanre', 'lgaAbbr' => 'WEN'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Ifedore', 'lgaAbbr' => 'FGB'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Ijaye', 'lgaAbbr' => 'GBA'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Ile-Oluji-Okeigbo', 'lgaAbbr' => 'LEL'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Irele', 'lgaAbbr' => 'REL'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Odigbo', 'lgaAbbr' => 'REF.'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Okitl-Pupa', 'lgaAbbr' => 'KTP'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Ondowtst', 'lgaAbbr' => 'NND'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Ondo-East', 'lgaAbbr' => 'BDR'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Ose', 'lgaAbbr' => 'FFN'],
    ['state' => 'Ondo', 'stateAbbr' => 'OD', 'lga' => 'Owo', 'lgaAbbr' => 'WWW'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Atakumosa', 'lgaAbbr' => 'SSU'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Atakumosa East', 'lgaAbbr' => 'PRN'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ayeda-Ade', 'lgaAbbr' => 'GBN'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ayedire', 'lgaAbbr' => 'LGB'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Boluwaduro', 'lgaAbbr' => 'TAN'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Boripe', 'lgaAbbr' => 'RGB'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ede', 'lgaAbbr' => 'EDE'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ede North', 'lgaAbbr' => 'EDT'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Egbedore', 'lgaAbbr' => 'AAW'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ejigbo', 'lgaAbbr' => 'EJG'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ife North', 'lgaAbbr' => 'PMD'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ife South', 'lgaAbbr' => 'FTD'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ife-Central', 'lgaAbbr' => 'FFE'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ife-East', 'lgaAbbr' => 'FEE'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ifedayo', 'lgaAbbr' => 'FDY'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ifelodun', 'lgaAbbr' => 'KNR'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ila', 'lgaAbbr' => 'LRG'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ilesa-East', 'lgaAbbr' => 'LES'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Llesa-West', 'lgaAbbr' => 'LEW'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Irepodun', 'lgaAbbr' => 'RLG'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Irewole', 'lgaAbbr' => 'KRE'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Isokan', 'lgaAbbr' => 'APM'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Iwo', 'lgaAbbr' => 'WWD'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Obokun', 'lgaAbbr' => 'BKN'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Odo-Otin', 'lgaAbbr' => 'DTN'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ola Oluwa', 'lgaAbbr' => 'BDS'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Olorunda', 'lgaAbbr' => 'GNN'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Ori-Ade', 'lgaAbbr' => 'JJS'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Orolu', 'lgaAbbr' => 'FNN'],
    ['state' => 'Osun', 'stateAbbr' => 'OS', 'lga' => 'Osogbo', 'lgaAbbr' => 'SGB'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Afijio', 'lgaAbbr' => 'JBL'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Akinyele', 'lgaAbbr' => 'MNY'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Atiba', 'lgaAbbr' => 'FMT'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Atigbo', 'lgaAbbr' => 'TDE'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Egbeda', 'lgaAbbr' => 'EGB'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Ibadan-North', 'lgaAbbr' => 'BDJ'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Ibadan-North-East', 'lgaAbbr' => 'AGG'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Ibadan-North-West', 'lgaAbbr' => 'MRK'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Ibadan-South-East', 'lgaAbbr' => 'MAP'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Ibadan-South-West', 'lgaAbbr' => 'LUY'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Ibarapa-Central', 'lgaAbbr' => 'RUW'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Ibarapa-East', 'lgaAbbr' => 'AYT'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Ibarapa-North', 'lgaAbbr' => 'IRP'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Ido', 'lgaAbbr' => 'DDA'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Irepo', 'lgaAbbr' => 'KSH'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Iseyin', 'lgaAbbr' => 'SEY'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => '1tesiwaju', 'lgaAbbr' => 'TUT'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Iwajowa', 'lgaAbbr' => 'WEL'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Kajola', 'lgaAbbr' => 'KEH'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Lagelu', 'lgaAbbr' => 'YNF'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Ogbomoso-North', 'lgaAbbr' => 'KNH'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Ogbomoso-South', 'lgaAbbr' => 'AME'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Ogo-Oluwa', 'lgaAbbr' => 'AJW'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Olorunsogo', 'lgaAbbr' => 'GBY'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Oluyole', 'lgaAbbr' => 'YRE'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Ona-Ara', 'lgaAbbr' => 'AKN'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Orelope', 'lgaAbbr' => 'GBH'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Ori-Ire', 'lgaAbbr' => 'KKY'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Oyo', 'lgaAbbr' => 'JND'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Oyo-East', 'lgaAbbr' => 'YYY'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Saki-East', 'lgaAbbr' => 'GMD'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Saki-West', 'lgaAbbr' => 'SHK'],
    ['state' => 'Oyo', 'stateAbbr' => 'OY', 'lga' => 'Surulere', 'lgaAbbr' => 'RSD'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Barkin-Ladi', 'lgaAbbr' => 'BLD'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Bassa', 'lgaAbbr' => 'BSA'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Bokkos', 'lgaAbbr' => 'BKK'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Jos-East', 'lgaAbbr' => 'ANW'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Jos-North', 'lgaAbbr' => 'JJN'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Jos-South', 'lgaAbbr' => 'BUU'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Kanam', 'lgaAbbr' => 'DNG'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Kanke', 'lgaAbbr' => 'KWK'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Langtang-North', 'lgaAbbr' => 'LGT'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Langtang-South', 'lgaAbbr' => 'MBD'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Mangu', 'lgaAbbr' => 'MGU'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Mikang', 'lgaAbbr' => 'TNK'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Pankshin', 'lgaAbbr' => 'PKN'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Quanan Pan', 'lgaAbbr' => 'QAP'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Riyom', 'lgaAbbr' => 'RYM'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Shendam', 'lgaAbbr' => 'SHD'],
    ['state' => 'Plateau', 'stateAbbr' => 'PL', 'lga' => 'Wase', 'lgaAbbr' => 'WAS'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Aboa/Odual', 'lgaAbbr' => 'ABU'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Ahoada-East', 'lgaAbbr' => 'AHD'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Ahoada-West', 'lgaAbbr' => 'KNM'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Akukutoru', 'lgaAbbr' => 'ABM'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Andoni', 'lgaAbbr' => 'NDN'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Asari-Toru', 'lgaAbbr' => 'BGM'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Bonny', 'lgaAbbr' => 'BNY'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Degema', 'lgaAbbr' => 'DEG'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Eleme', 'lgaAbbr' => 'NCH'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Emuoha', 'lgaAbbr' => 'MHA'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Etche', 'lgaAbbr' => 'KHE'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Gokana', 'lgaAbbr' => 'KPR'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Kwerre', 'lgaAbbr' => 'SKP'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Khana', 'lgaAbbr' => 'BRR'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Obia/Akpor', 'lgaAbbr' => 'RUM'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Ogba-Egbema-Ndoni', 'lgaAbbr' => 'RGM'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Ogu/Bolo', 'lgaAbbr' => 'GGU'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Okirika', 'lgaAbbr' => 'KRK'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Omuma', 'lgaAbbr' => 'BER'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Opobo/Nkoro', 'lgaAbbr' => 'PBT'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Oyigbo', 'lgaAbbr' => 'AFM'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Port-Harcourt', 'lgaAbbr' => 'PHC'],
    ['state' => 'Rivers', 'stateAbbr' => 'RV', 'lga' => 'Tai', 'lgaAbbr' => 'SKN'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Binji', 'lgaAbbr' => 'BJN'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Bodinga', 'lgaAbbr' => 'DBN'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Dange-Shuni', 'lgaAbbr' => 'DGS'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Gada', 'lgaAbbr' => 'GAD'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Goronyo', 'lgaAbbr' => 'GRY'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Gudu', 'lgaAbbr' => 'BLE'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Gwadabawa', 'lgaAbbr' => 'GWD'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Illela', 'lgaAbbr' => 'LLA'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Isa', 'lgaAbbr' => 'SAA'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Kebbe', 'lgaAbbr' => 'KBE'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Kware', 'lgaAbbr' => 'KWR'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Rabah', 'lgaAbbr' => 'RBA'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Sabon-Birni', 'lgaAbbr' => 'SBN'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Shagari', 'lgaAbbr' => 'SGR'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Silame', 'lgaAbbr' => 'SLM'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Sokoto-North', 'lgaAbbr' => 'SKK'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Sokoto-South', 'lgaAbbr' => 'SRZ'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Tambawal', 'lgaAbbr' => 'TBW'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Tangaza', 'lgaAbbr' => 'TGZ'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Tureta', 'lgaAbbr' => 'TRT'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Wamakko', 'lgaAbbr' => 'WMK'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Wurno', 'lgaAbbr' => 'WRN'],
    ['state' => 'Sokoto', 'stateAbbr' => 'SO', 'lga' => 'Yabo', 'lgaAbbr' => 'YYB'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Ardo-Kola', 'lgaAbbr' => 'ARD'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Bali', 'lgaAbbr' => 'BAL'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Donga', 'lgaAbbr' => 'DGA'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Gashaka', 'lgaAbbr' => 'GKA'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Gassol', 'lgaAbbr' => 'GAS'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Ibi', 'lgaAbbr' => 'BBB'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Jalingo', 'lgaAbbr' => 'JAL'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Karim-Lamido', 'lgaAbbr' => 'KLD'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Kurmi', 'lgaAbbr' => 'KRM'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Lau', 'lgaAbbr' => 'LAU'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Sardauna', 'lgaAbbr' => 'SDA'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Takum', 'lgaAbbr' => 'TTM'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Ussa', 'lgaAbbr' => 'USS'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Wukari', 'lgaAbbr' => 'WKR'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Yorro', 'lgaAbbr' => 'YRR'],
    ['state' => 'Taraba', 'stateAbbr' => 'TB', 'lga' => 'Zing', 'lgaAbbr' => 'TZG'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Bade', 'lgaAbbr' => 'GSH'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Bosari', 'lgaAbbr' => 'DPH'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Damaturu', 'lgaAbbr' => 'DTR'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Fika', 'lgaAbbr' => 'FKA'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Fune', 'lgaAbbr' => 'FUN'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Geidam', 'lgaAbbr' => 'GDM'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Gujba', 'lgaAbbr' => 'GJB'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Gulani', 'lgaAbbr' => 'GLN'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Jakusko', 'lgaAbbr' => 'JAK'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Karasuwa', 'lgaAbbr' => 'KRS'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Machina', 'lgaAbbr' => 'MCN'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Nangere', 'lgaAbbr' => 'NNR'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Nguru', 'lgaAbbr' => 'NGU'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Potiskum', 'lgaAbbr' => 'PKM'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Tarmua', 'lgaAbbr' => 'TMW'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Yunusari', 'lgaAbbr' => 'YUN'],
    ['state' => 'Yobe', 'stateAbbr' => 'YB', 'lga' => 'Yusufari', 'lgaAbbr' => 'YSF'],
    ['state' => 'Zamfara', 'stateAbbr' => 'ZA', 'lga' => 'Anka', 'lgaAbbr' => 'ANK'],
    ['state' => 'Zamfara', 'stateAbbr' => 'ZA', 'lga' => 'Bakura', 'lgaAbbr' => 'BKA'],
    ['state' => 'Zamfara', 'stateAbbr' => 'ZA', 'lga' => 'Bukkuyum', 'lgaAbbr' => 'BKM'],
    ['state' => 'Zamfara', 'stateAbbr' => 'ZA', 'lga' => 'Bungudu', 'lgaAbbr' => 'BUG'],
    ['state' => 'Zamfara', 'stateAbbr' => 'ZA', 'lga' => 'Gumi', 'lgaAbbr' => 'GMM'],
    ['state' => 'Zamfara', 'stateAbbr' => 'ZA', 'lga' => 'Gusau', 'lgaAbbr' => 'GUS'],
    ['state' => 'Zamfara', 'stateAbbr' => 'ZA', 'lga' => 'Kaura-Namoda', 'lgaAbbr' => 'KRN'],
    ['state' => 'Zamfara', 'stateAbbr' => 'ZA', 'lga' => 'Birnin Magaji', 'lgaAbbr' => 'BMJ'],
    ['state' => 'Zamfara', 'stateAbbr' => 'ZA', 'lga' => 'Maradun', 'lgaAbbr' => 'MRD'],
    ['state' => 'Zamfara', 'stateAbbr' => 'ZA', 'lga' => 'Maru', 'lgaAbbr' => 'MRR'],
    ['state' => 'Zamfara', 'stateAbbr' => 'ZA', 'lga' => 'Shinkafi', 'lgaAbbr' => 'SKF'],
    ['state' => 'Zamfara', 'stateAbbr' => 'ZA', 'lga' => 'Talata-Mafara', 'lgaAbbr' => 'TMA'],
    ['state' => 'Zamfara', 'stateAbbr' => 'ZA', 'lga' => 'Tsafe', 'lgaAbbr' => 'TSF'],
    ['state' => 'Zamfara', 'stateAbbr' => 'ZA', 'lga' => 'Zurmi', 'lgaAbbr' => 'ZRM'],
  ];